### ISSUE TITLE
Borg-Reduce creates two 'id' columns for Gephi

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/borg-reducer#2]
🎉 it's working, and `--file` is now loading in our custom data.

The only thing I'd flag is that it currently creates an `Id` (upper case) column with the node identifiers and then an `id` (lower case) column with the unique node names. Any way to make that easier to follow?

Screenshot example:
![fullscreen_2018-01-28__8_26_pm](https://user-images.githubusercontent.com/3834704/35489976-176af1a2-046a-11e8-861e-9edfc7aa0b62.png)

Right now to make it work you need to copy the label data from `id` - somewhat challenging to know the exact column to select as they're so close. 😄

**Comment by greebie** [comment]
It should be fairly easy to copy the Id label to "Label" instead.

**Comment by greebie** [comment]
This was an interfacing to aut thing, but has been resolved.
